#!/bin/bash
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:
CALCHEP=/Users/linusong/Documents/DMDiscovery/calchep_3.9.1
export CALCHEP
WORK=`pwd`
export WORK
. $CALCHEP/FlagsForSh

$CALCHEP/bin/s_calchep $*
if(test $? -ne 22) then echo error in C-code generation; exit 1 ;fi
$CALCHEP/bin/s_calchep -blind "[{{[{0" 
if(test -x results/n_calchep) then 
   echo n_calchep is created
   exit 0
else 
   echo error in n_calchep linking
    exit 3 
fi   

